version: 1
loggers:
    default_logger:
        handlers: [consoleHandler]
        level: DEBUG
handlers:
    consoleHandler:
        class: logging.StreamHandler
        level: DEBUG
        formatter: brief
formatters:
    brief:
        format: '%(levelname)8s %(message)s'

