[project]
name = "manage-resource-using-with-resource"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "click>=8.1.8",
    "loguru>=0.7.3",
]

[dependency-groups]
dev = [
    "ruff>=0.14.2",
]
