[project]
name = "rest-pagination"
version = "0.1.0"
description = "RESTful Web Services API Pagination"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "ruff>=0.9.10",
]
