SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 1000

BALLS_PER_COLUMN = 8
BALL_GAP = 20
BALL_RADIUS = 40
BALL_OUTLINE_THICKNESS = 5

COLUMNS_COUNT = 8
COLUMN_HEIGHT = 800
COLUMN_WIDTH = 100

VERTICAL_MARGIN = 2 * (BALL_GAP * 2 + BALL_RADIUS)

LINE_THICKNESS = 5
