.PHONY: nginx wfh3 f5

nginx: ~/.virtualenv/pillow
	bash add_logo.sh --logo logos/nginx-plus.png --input-dir pictures --output-dir output-nginx-plus

wfh3:
	bash add_logo.sh --logo logos/wfh3.png --input-dir pictures --output-dir output-wfh3

f5: 
	bash add_logo.sh --logo logos/f5-logo-white.png --input-dir pictures --output-dir output-f5-white

~/.virtualenv/pillow:
	bash create-virtualenv.sh

