[project]
name = "fabric-reboot-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fabric>=3.2.2",
    "loguru>=0.7.3",
    "paramiko>=3.5.1",
]

[dependency-groups]
dev = [
    "ipython>=9.4.0",
    "ruff>=0.12.10",
]
