BALLS_PER_COLUMN = 8
BALL_GAP = 20
BALL_RADIUS = 40
BALL_OUTLINE_THICKNESS = 5

COLUMNS_COUNT = 8
COLUMN_HEIGHT = (BALL_RADIUS + BALL_GAP) * BALLS_PER_COLUMN
COLUMN_WIDTH = BALL_RADIUS + (BALL_GAP * 4)

VERTICAL_MARGIN = 2 * (BALL_GAP * 2 + BALL_RADIUS)

SCREEN_WIDTH = (BALL_RADIUS + (5 * BALL_GAP)) * COLUMNS_COUNT
SCREEN_HEIGHT = (BALL_RADIUS + (4 * BALL_GAP)) * (BALLS_PER_COLUMN + 0)


LINE_THICKNESS = 5
