[project]
name = "inspect-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
    "ipython>=9.0.2",
]
