[project]
name = "first-celery-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "celery>=5.4.0",
    "loguru>=0.7.3",
]

[dependency-groups]
dev = [
    "ipython>=9.0.2",
    "ruff>=0.11.2",
]
