[project]
name = "pens"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hai Vu", email = "haivu2004@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.5",
    "requests>=2.34.2",
]

[project.scripts]
pens = "pens:__main__.main"

[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipython>=9.16.0",
    "pudb>=2025.1.5",
    "ruff>=0.16.1",
]
