[project]
name = "shell-variable-expansion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click==8.1.7",
]

[dependency-groups]
dev = [
    "ipython>=9.6.0",
    "pyrefly>=0.37.0",
    "pytest>=8.4.2",
    "ruff>=0.14.0",
]
