[project]
name = "jq-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jq>=1.8.0",
    "rich>=13.9.4",
]

[dependency-groups]
dev = [
    "ipython>=9.0.2",
    "ruff>=0.11.2",
]
