[project]
name = "typer-slim-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "typer-slim>=0.15.2",
]

[dependency-groups]
dev = [
    "ruff>=0.11.0",
]
