run:
	python3 name_value_using_action.py
	@echo "========================================"
	python3 name_value_using_action.py -d uid=501 alias=john -d is_admin -d groups='["wheel", "bak"]'
	@echo "========================================"
	python3 name_value_using_function.py
	@echo "========================================"
	python3 name_value_using_function.py -d uid=501 alias=john -d is_admin -d groups='["wheel", "bak"]'

