demo:
	pycheck .
	uv run mksuite.py peter paul mary
	@echo "---"
	uv run mksuite.py single --name=mysuit
	@echo "---"
	uv run example2_class.py set foo 1995
	@echo "---"
	uv run example2_class.py get foo

