[project]
name = "pattern-matching"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hai Vu", email = "haivu2004@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
]

[project.scripts]
pattern-matching = "pattern_matching:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
    "ipython>=9.0.2",
    "pudb>=2024.1.3",
    "pytest>=8.3.5",
    "ruff>=0.11.2",
]
