[project]
name = "change-tracker-dict"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hai Vu", email = "haivu2004@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
change-tracker-dict = "change_tracker_dict:main"

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipython>=9.6.0",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.0",
    "ty>=0.0.1a22",
]

[tool.pytest.ini_options]
addopts = "--cov=change_tracker_dict --no-cov-on-fail"

[tool.coverage.run]
omit = ["src/change_tracker_dict/main.py"]

[tool.coverage.html]
directory = "coverage"

