[project]
name = "boto-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.39.14",
]

[dependency-groups]
dev = [
    "ipython>=9.4.0",
    "ruff>=0.12.5",
]
